FROM nexus.cooperforte.coop:9090/nginx-openshift:latest
LABEL maintainer="Douglas Ramiro <douglas@cf.coop.br>"


RUN apt update && \
    apt install curl wget -y && \
     rm -rf /var/lib/apt/lists/*


