FROM centos:7

#WORKDIR /
ADD dinamo-4.2.3-1.x64-linux-centos.tar.gz /tmp
#ADD teste.tar.gz .
RUN cp -ra /tmp/dinamo-4.2.3-1.x64-linux-centos/* / && rm -rf /tmp/dinamo-4.2.3-1.x64-linux-centos 

RUN chmod +x /usr/bin/hsmcon
#CP 
