image: nexus.brb.com.br:6000/arq/gitlab-cicd-node:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
#  key: ${CI_PROJECT_ID}
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/

checkout:
  stage: checkout
  cache: []
  tags:
    - projetosjava
  script:
    - | 
        git config --global user.name ${GITLAB_USER_NAME} && \
        git config --global user.email ${GITLAB_USER_EMAIL} && \
        git config --global push.default simple
    - git config --global http.sslVerify false
    - git remote set-url --push origin "${CI_REPOSITORY_URL}"
    - git checkout -B "${CI_COMMIT_REF_NAME}" "${CI_COMMIT_SHA}"
#    - npm cache clear --force 
#    - npm install --no-shrinkwrap --update-binary 
#    - npm run build
  only:
    - desen
    - hmlg
    - master

install_dependencies:
  stage: install_dependencies
  tags:
    - projetosjava
  script:
    - npm ci
#  cache:
#    key: $CI_PROJECT_ID
#    paths:
#      - node_modules/
  only:
    refs:
      - desen
      - hmlg
      - master
    changes:
      - package.json

build:
  stage: build
  tags:
    - projetosjava
#  cache: 
#    key: $CI_PROJECT_ID
#    paths:
#      - node_modules/    
  artifacts:
    expire_in: 60 mins
    paths:
      - dist/
  script:
    - npm run build
  only:
    - desen
    - hmlg
    - master

deploy-desen:
  image: nexus.brb.com.br:6000/arq/gitlab-cicd-oc:latest
  stage: deploy
  cache: []
  tags:
    - projetosjava
  dependencies:
    - build
  script:
    - echo "${OPENSHIFT_PROD_USERNAME} ${OPENSHIFT_PROD_PASSWORD} ${OPENSHIFT_PROD_URL}"
    - oc login -u "${OPENSHIFT_PROD_USERNAME}" -p "${OPENSHIFT_PROD_PASSWORD}" "${OPENSHIFT_PROD_URL}" --insecure-skip-tls-verify
# sem deploys para commits na desen
#    - oc project "${OPENSHIFT_PROJECT_DEV}"
#    - oc start-build "${OPENSHIFT_BC_NAME}" --from-dir="." --follow    
#    - oc get build | grep "${OPENSHIFT_BC_NAME}" | tail -1 | grep Complete
  only:
    - desen


deploy-hmlg:
  image: nexus.brb.com.br:6000/arq/gitlab-cicd-oc:latest
  stage: deploy
  cache: []
  tags:
    - projetosjava
  dependencies:
    - build
  script:
    - oc login -u "${OPENSHIFT_PROD_USERNAME}" -p "${OPENSHIFT_PROD_PASSWORD}" "${OPENSHIFT_PROD_URL}" --insecure-skip-tls-verify
    - oc project "${OPENSHIFT_PROJECT_HOMOL}"
    - oc start-build "${OPENSHIFT_BC_NAME}" --from-dir="." --follow   
    - oc get build | grep "${OPENSHIFT_BC_NAME}" | tail -1 | grep Complete
  only:
    - hmlg    

deploy-trt:
  image: nexus.brb.com.br:6000/arq/gitlab-cicd-oc:latest
  when: manual
  stage: deploy-trt
  cache: []
  tags:
    - projetosjava
  dependencies:
    - build
  script:
    - oc login -u "${OPENSHIFT_PROD_USERNAME}" -p "${OPENSHIFT_PROD_PASSWORD}" "${OPENSHIFT_PROD_URL}" --insecure-skip-tls-verify
    - oc project "${OPENSHIFT_PROJECT_TRT}"
    - oc start-build "${OPENSHIFT_BC_NAME}" --from-dir="." --follow   
    - oc get build | grep "${OPENSHIFT_BC_NAME}" | tail -1 | grep Complete
  only:
    - hmlg    


deploy-prd:
  image: nexus.brb.com.br:6000/arq/gitlab-cicd-oc:latest
  stage: deploy
  cache: []
  tags:
    - projetosjava
  dependencies:
    - build
  script:
    - oc login -u "${OPENSHIFT_PROD_USERNAME}" -p "${OPENSHIFT_PROD_PASSWORD}" "${OPENSHIFT_PROD_URL}" --insecure-skip-tls-verify
    - oc project "${OPENSHIFT_PROJECT_PROD}"
    #- oc start-build "${OPENSHIFT_BC_NAME}" --from-dir="." --follow   
    #- oc get build | grep "${OPENSHIFT_BC_NAME}" | tail -1 | grep Complete
  only:
    - master    